### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by brettgaylor** [rknLA/irc-slack-echo#1]
Was having a conversation with folks at @slackhq and they pointed at this :+1: any thoughts on bringing slack conversations back to IRC?

**Comment by rknLA** [comment]
Yeah, I was thinking about adding an outgoing hook to the bot to listen for something like `!reply the message I want to send to IRC`, but all of the chatter going into IRC would come from the bot, so it could be awkward.

**Comment by brettgaylor** [comment]
right.  Though if it just added the slack username it might make sense.  Would be nice to be able to use the slack workflow but still communicate with contributors or users in IRC that are outside of team.

Also, huge rdio fan, nice work :)

**Comment by rknLA** [comment]
d847b9e8c7b77f8 and d5833e8ba9171e add support for `!say things` to echo stuff back to IRC.  You'll need to create an outgoing webhook to make it work, and I haven't updated the documentation to reflect that yet.
